spring.application.name=mes

# DataSource
spring.datasource.url=${MES_DB_URL:jdbc:mysql://localhost:3306/mes}
spring.datasource.username=${MES_DB_USERNAME:root}
spring.datasource.password=${MES_DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Server
server.port=${SERVER_PORT:8080}

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

# Logger
logging.level.root=${LOG_ROOT:INFO}
logging.level.com.example=${LOG_MES:DEBUG}

# MyBatis
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mappers/*.xml
